# Generated by Django 5.0.7 on 2024-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_siteuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='profile_picture',
            field=models.ImageField(default='media/default_ava.jpg', upload_to='profile_picture'),
        ),
    ]
